apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  meshConfig:
    extensionProviders:
      - name: "opa"
        envoyExtAuthzGrpc:
          service: "opa.opa.svc.cluster.local"
          port: "9191"
