namespace: opa

configMapGenerator:
  # The OPA policy
  - name: opa-policy
    files:
      - policy/credentials.rego
      - policy/envoy_authz.rego
      - policy/static_secret_jwt.rego
      - policy/apps/httpbin.rego
      - policy/apps/podinfo.rego
  - name: opa-data
    files:
      - data/config.yaml

secretGenerator:
  - name: opa-secrets
    envs:
      - secrets/secrets.env

resources:
  - opa.yaml
  - namespace.yaml
